---
name: Build tests

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions: read-all
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm64

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install \
            gnutls-dev \
            libkeyutils-dev \
            libnl-3-dev \
            libnl-genl-3-dev \
            libglib2.0-dev

      - name: Configure
        run: |
          ./autogen.sh
          ./configure --with-systemd

      - name: Build
        run: make

      - name: Check
        run: make check

      - name: Distcheck
        run: make distcheck
