name: "Generate release assets"

on:
  push:
    tags:
      - "ktls-utils-*"

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    - name: "Install dependencies"
      run: |
        sudo apt-get update
        sudo apt-get -y install gnutls-dev libkeyutils-dev libnl-3-dev libnl-genl-3-dev

    - name: "Instantiate autotools"
      run: ./autogen.sh

    - name: "Configure build environment"
      run: ./configure --with-systemd

    - name: "Build release asset"
      run: make dist

    - name: "Version"
      run: |
        echo "ktls_utils_version=`./configure --version | awk '{print $3;; exit}'`" >> $GITHUB_ENV

    - name: "Create release"
      uses: ncipollo/release-action@v1
      id: create_release
      with:
        artifacts: ktls-utils-${{ env.ktls_utils_version }}.tar.gz
        artifactContentType: application/gzip
        bodyFile: NEWS
        name: v${{ env.ktls_utils_version }}
        tag: ${{ github.ref }}
